### ISSUE TITLE
ESLint dependency

### ISSUE THREAD

**Issue by ogandose** [Neovici/github-actions-eslint-annotator#4]
Hi 🙂 I was just wondering one more thing, is it necessary to have this hard dependency on ESLint 5?

**Comment by nomego** [comment]
Probably not! We can likely switch it to `>= 5` but that's what we're on and testing it with at the moment. Are you running this with ESLint 6?

**Comment by ogandose** [comment]
We're actually also using ESLint 5. After I posted this I noticed that I'm not really using your dependency since I'm installing them all separately to avoid running `npm install` since we have quite a lot of dependencies. Do you possibly have an idea how this could be avoided?

**Comment by ogandose** [comment]
`on:
  pull_request:
  push:
    branches:
      - master
 
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: install eslint
      run: | 
             npm install eslint@5.2.0
             npm install babel-eslint@^9.0.0
             npm install eslint-plugin-amd-imports@^4.0.0
             npm install eslint-plugin-jest@^21.18.0
             npm install eslint-plugin-prettier@^2.6.2
             npm install eslint-plugin-react@^7.10.0
             npm install eslint-plugin-react-hooks@^1.6.1
             npm install eslint-plugin-requirejs@^4.0.0
             npm install prettier@^1.18.2
             npm install @neovici/github-actions-eslint-annotator
         
    - name: ESLint Annotations
      run: npx github-actions-eslint-annotator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PARTIAL_LINTING: true`

**Comment by ogandose** [comment]
Yes, this is the whole worklflow. Mostly because we have a lot of dependencies and it takes quite long and we also have dependencies on the internal registry.

**Comment by nomego** [comment]
I would extend the workflow to include more steps like tests and you'll likely end up in a situation where you need more and more npm stuff and end up starting with an "npm install" and just keeping your deps in there.

But in theory, you don't need to install this annotator with `npm install` but rather just run:

`npx @neovici/github-actions-eslint-annotator@latest`

and npm should install whatever is necessary.
I did have some problems with this when I tried but please have a go at it you too.
It would not, however, solve your other installs like additional eslint plugins.

**Comment by ThiefMaster** [comment]
:+1: on `>=5`

I'm already installing eslint 6 from my package.json during an `npm install` step and I'm pretty sure my eslint config isn't compatible with eslint 5 anymore...
