### ISSUE TITLE
Support for other than .js files

### ISSUE THREAD

**Issue by fabulator** [Neovici/github-actions-eslint-annotator#6]
Hi, 

I'm using eslint for checking typescript files (.ts) but this package allows only .js files. Would be possible to customize file extensions that are being processed?

**Comment by nathan815** [comment]
Did you ever figure this out, or find another functional eslint annotator action that supports typescript?

**Comment by fabulator** [comment]
> Did you ever figure this out, or find another functional eslint annotator action that supports typescript?

Nope, I sticked with the Circle CI until some features are developed for Github Action. So I didn't continue with trying eslint annotator.
